version: 5.0.1-{branch}+{build}

image: Visual Studio 2015

environment:
  matrix:
  - MSYSTEM: MINGW64

artifacts:
  - path: '*nightly.exe'

build_script:
  - C:\msys64\usr\bin\pacman -Syuu --noconfirm
  - C:\msys64\usr\bin\bash -lc "$(cygpath ${APPVEYOR_BUILD_FOLDER})/.appveyor_build.sh"

deploy:
  tag: nightly
  description: 'Nightly build from the latest successful commit'
  provider: GitHub
  auth_token:
    secure: 662Gozhe3fmtaVUptOYmok9ayZxuk9PDVS6pN8QfZPwP+P102GV5SnSpHcDR1o77 # your encrypted token from GitHub
    artifact: /.*\nightly.exe/ # artifact to release
  prerelease: true
  force_update: true
