version: 1.0.{build}

image: Visual Studio 2015

environment:
  matrix:
  - COMPILER: msys2
    PLATFORM: x64
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    BIT: 64
  
install:
  - set PATH=C:\%MSYS2_DIR%\%MSYSTEM%\bin;C:\%MSYS2_DIR%\usr\bin;%PATH% #msys2
  - bash -lc "pacman -Syu --noconfirm"
  - bash -lc "pacman --sync --noconfirm mingw-w64-x86_64-toolchain" # msys64-only
  - bash -lc "pacman -S mingw-w64-x86_64-boost --noconfirm"
  - bash -lc "pacman -S mingw-w64-x86_64-python2 --noconfirm"
  - bash -lc "pacman -S mingw-w64-x86_64-qt5 --noconfirm"
  - bash -lc "pacman -S mingw-w64-x86_64-ninja --noconfirm"
  - bash -lc "pacman -S mingw-w64-x86_64-quazip --noconfirm"
  - bash -lc "pacman -S mingw-w64-x86_64-snappy --noconfirm"
  
  ####
  # Download and install PythonQt
  ####
  - bash -lc "curl -L https://doc-0s-74-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/73db5g840m3bs8bgjn4bpu19mkofplbj/1486382400000/18428009403027643723/*/0B1vZJx8YIElmcTJpNjFWWFlvQVE?e=download > pythonqt.tar.xz"
  - bash -lc "tar xvf pythonqt.tar.xz"

  ####
  # Build Knossos
  ####
  - bash -lc "mkdir knossos-build"
  - bash -lc "cd knossos-build && cmake -G Ninja -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_PREFIX_PATH='/home/appveyor/mingw64/qt5-static/lib/cmake' /c/projects/knossos"
  
build_script:
  - bash -lc "cd knossos-build && ninja -j2"
