version: 5.1-{branch}+{build}

image: Visual Studio 2015

environment:
  matrix:
  - MSYSTEM: MINGW64

artifacts:
  - path: '*nightly.exe'

build_script:
  - C:\msys64\usr\bin\pacman -Syuu --noconfirm
  - C:\msys64\usr\bin\bash -lc "$(cygpath ${APPVEYOR_BUILD_FOLDER})/ci/appveyor_build.sh"

deploy:
  - provider: GitHub
    tag: nightly
    description: 'Nightly build from the latest successful commit'
    auth_token:
      secure: 9tKkhsqR9qSoKt3390923aZ0EauffZQQ/6Ho0HdYlTEudtFJ1eTnw6B3TGclgqA0 # your encrypted token from GitHub
      artifact: /.*\nightly.exe/ # artifact to release
    prerelease: true
    force_update: true
    on:
      branch: master
  - provider: GitHub
    tag: nightly-dev
    description: 'Nightly build from the latest successful commit'
    auth_token:
      secure: 9tKkhsqR9qSoKt3390923aZ0EauffZQQ/6Ho0HdYlTEudtFJ1eTnw6B3TGclgqA0 # your encrypted token from GitHub
      artifact: /.*\nightly.exe/ # artifact to release
    prerelease: true
    force_update: true
