language: cpp

compiler:
  - clang
  - gcc

before_install:
  - lsb_release -a
  - sudo apt-add-repository -y ppa:jkeiren/ppa
  - if test $CC = gcc; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo add-apt-repository -y ppa:kalakris/cmake # CMake 2.11.2
  - sudo apt-add-repository -y ppa:ubuntu-sdk-team/ppa
  - sudo apt-add-repository -y ppa:beineri/opt-qt521
  - sudo apt-add-repository -y ppa:arankine/backports#ninja-build 1.3.4
  - sudo apt-add-repository -y ppa:yjwong/libjpeg-turbo#libjpeg-turbo 1.3.0
  - sudo apt-add-repository -y ppa:georgekola/clang#libc++ (llvm 3.2)
  - sudo apt-get update -qq
  - sudo apt-get -qq install cmake
  - sudo apt-get -qq install freeglut3-dev
  - sudo apt-get -qq install libc++
  - sudo apt-get -qq install libcurl4-openssl-dev
  - sudo apt-get -qq install libjpeg-turbo8-dev
  - sudo apt-get -qq install libxmu-dev libxi-dev
  - sudo apt-get -qq install ninja-build
  - sudo apt-get -qq install qt52base qt52tools
  - if test $CC = gcc; then sudo apt-get install -qq gcc-4.8 g++-4.8; fi
  - if test $CC = gcc; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20; fi
  - if test $CC = gcc; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20; fi
  - if test $CC = gcc; then sudo update-alternatives --config gcc; fi
  - if test $CC = gcc; then sudo update-alternatives --config g++; fi
  - source /opt/qt52/bin/qt52-env.sh

before_script:
  - mkdir build_debug
  - cd build_debug
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=DEBUG ..
  - cd ..
  - mkdir build_release
  - cd build_release
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=RELEASE ..
  - cd ..

script:
  - cd build_debug
  - ninja
  - cd ..
  - cd build_release
  - ninja
  - cd ..