language: minimal

git:
  depth: false # tags for git describe may be farther away than the default depth

matrix:
  include:
    - os: osx
      sudo: enabled
      env: TRAVIS_TAG=nightly-dev
      addons:
        homebrew:
          packages:
            - boost
            - ninja
            - qt
            - quazip
            - snappy

script:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then sh $TRAVIS_BUILD_DIR/ci/build_macos.sh; fi

deploy:
  - provider: releases
    api_key:
      secure: "DHBayH59cTgSeuzw0umwjc52r5p1sR3EV1vOG77cK1NIb7fi2UVmx69V2mIzfGYp0t1uFDsVvDGtFYRQxKozCteBu2oinmbiSjbeWnyldQqTFnF4QONF+eWGiHNdOdHY7Tj37+eV5BlgfsXZ5MfLN3tXZ2y++D+yfoUItsbvC3I="
    file_glob: true
    file:
      - "*.zip"
    skip_cleanup: true
    overwrite: true
    on:
      repo: knossos-project/knossos
      all_branches: true
      condition: $TRAVIS_TAG = nightly-dev
