env:
  global:
    - TRAVIS_TAG=nightly-dev

language: minimal

matrix:
  include:
    - os: linux
      dist: xenial
      services: docker
    - os: osx
      sudo: enabled
      addons:
        homebrew:
          packages:
            - boost
            - ninja
            - qt
            - quazip
            - snappy

script:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then docker pull knossostool/knossos; fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then docker run -it --privileged --cap-add=ALL -v /lib/modules:/lib/modules -v /dev:/dev -v ${PWD}:/root/knossos -e TRAVIS_BRANCH knossostool/knossos bash -c '/root/knossos/ci/travis_build.sh'; fi
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then sh $TRAVIS_BUILD_DIR/ci/build_macos.sh; fi

deploy:
  - provider: releases
    api_key:
      secure: "DHBayH59cTgSeuzw0umwjc52r5p1sR3EV1vOG77cK1NIb7fi2UVmx69V2mIzfGYp0t1uFDsVvDGtFYRQxKozCteBu2oinmbiSjbeWnyldQqTFnF4QONF+eWGiHNdOdHY7Tj37+eV5BlgfsXZ5MfLN3tXZ2y++D+yfoUItsbvC3I="
    file_glob: true
    file:
      - "*.AppImage"
      - "macos.*.zip"
    skip_cleanup: true
    overwrite: true
    on:
      repo: knossos-project/knossos
      all_branches: true
